# Generated by Django 5.2.3 on 2025-06-23 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(help_text='Выберите курс', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='materials.course', verbose_name='lessons'),
        ),
    ]
