# Generated by Django 5.2.3 on 2025-07-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("materials", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
