# Generated by Django 5.2.3 on 2025-08-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_course_last_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="amount",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Введите цену курса",
                null=True,
                verbose_name="Цена",
            ),
        ),
    ]
