# Generated by Django 5.2.3 on 2025-08-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_alter_lesson_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="amount",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Введите цену курса",
                null=True,
                verbose_name="Цена",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="amount",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Введите цену курса",
                null=True,
                verbose_name="Цена",
            ),
        ),
    ]
